site_name: ALS TDI Real World Evidence Resources

theme:
  name: material
  logo: assets/ALSTDI-logo-stacked-color.png
  font:
    text: "EB Garamond"   # Google Fonts – Material auto-loads it
  palette:
    scheme: default
    primary: custom        # tells Material to use the CSS variables below
    accent: custom
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.header

nav:
  - Home: index.md
  - Introduction: introduction.md
  - STARDUSTT Approach: stardustt-approach.md
  - ALS TDI OMOP Data Set: als-tdi-omop-data-set.md
  - OMOP/OHDSI Resources: omop-ohdsi-resources.md
  - Free RWE Resources: free-rwe-resources.md
  - Select Publications: select-publications.md
  - Authors: authors.md

markdown_extensions:
  - meta

extra:
  generator: false

extra_css:
  - assets/css/custom.css