site_name: ALS TDI Real World Evidence Resources

theme:
  name: material
  palette:
    primary: deep purple
    accent: purple
  logo: assets/ALSTDI-logo-stacked-color.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.header

nav:
  - Home: index.md
  - Introduction: introduction.md
  - ALS TDI OMOP Data Set: als-tdi-omop-data-set.md
  - OMOP/OHDSI Resources: omop-ohdsi-resources.md
  - Free RWE Resources: free-rwe-resources.md
  - Authors: authors.md

markdown_extensions:
  - meta

extra:
  generator: false  # Removes the "Made with MkDocs" footer for a cleaner look

extra_css:
  - assets/css/custom.css
