site_name: ALS-RWE Documentation
theme:
  name: material
nav:
  - Home: index.md
  - Introduction: introduction.md
  - ALS TDI OMOP Data Set: als-tdi-omop-data-set.md
  - OMOP OHDSI Resources: omop-ohdsi-resources.md
  - Free RWE Resources: free-rwe-resources.md
  - Author: author.md
