site_name: ALS TDI Real World Evidence Resources
site_url: https://alstdi.github.io/ALS-RWE/
repo_url: https://github.com/ALSTDI/ALS-RWE
repo_name: ALSTDI/ALS-RWE

theme:
  name: material
  logo: assets/ALSTDI-logo-stacked-color.png
  favicon: assets/ALSTDI-logo-stacked-color.png
  font:
    text: "EB Garamond"   # Material will load from Google Fonts
  palette:
    scheme: default       # keep light mode for now
    primary: custom       # use our CSS variables below
    accent: custom
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.header
  

nav:
  - Home: index.md
  - Introduction: introduction.md
  - ALS TDI OMOP Data Set: als-tdi-omop-data-set.md
  - OMOP/OHDSI Resources: omop-ohdsi-resources.md
  - Free RWE Resources: free-rwe-resources.md
  - Authors: authors.md

markdown_extensions:
  - meta

extra:
  generator: false  # remove "Made with MkDocs"

extra_css:
  - assets/css/custom.css
